### ISSUE TITLE
mvn exec:java ClassNotFoundException

### ISSUE THREAD

**Issue by ghost** [serhiy/cglib-example-1#1]
> [WARNING]
java.lang.ClassNotFoundException: xyz.codingdaddy.cglib.ACMEMain
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:285)
	at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------

**Comment by serhiy** [comment]
Hello, in order to help me investigating further the issue, could you please check whether the directory you are executing Maven command is something like: <example location>/cglib-example-1/. Additionally could you please indicate Maven version you are using (mvn --version command can be used, I only need the first line of the output). Thanks.

**Comment by ghost** [comment]
➜  cglib-example-1 git:(master) pwd
/Volumes/Macintosh HD/github/cglib-example-1
➜  cglib-example-1 git:(master) mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"

➜  cglib-example-1 git:(master) mvn exec:java
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building cglib-example-1 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) > validate @ cglib-example-1 >>>
[INFO]
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) < validate @ cglib-example-1 <<<
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ cglib-example-1 ---
 --- Adding message ---
 --- Listing messages ---
1526459066929 : <test> : Hello message 1.
 --- Last message timestamp ---
1526459066929
 --- Adding message (not authenticated) ---
User must be authenticated to invoke addMessage() method.
 --- Listing messages (not authenticated) ---
1526459066929 : <test> : Hello message 1.
 --- Last message timestamp (not authenticated) ---
1526459066929
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.411 s
[INFO] Finished at: 2018-05-16T16:24:26+08:00
[INFO] Final Memory: 10M/309M

**thanks a lot ,this time it build succss**

**Comment by serhiy** [comment]
Great :)
